name: Test
on: pull_request

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install dependencies
        run: yarn install
      - name: Lint
        run: yarn lint
      - name: Unit tests
        run: yarn test
      - name: Integration tests
        run: yarn test:integration
